name: Bug report
description: Report an issue to help us improve
labels: ["bug"]
body:
  - type: dropdown
    id: platform
    attributes:
      label: Android or Web
      description: Does this issue occur on the Android or Web version of Win7 Simu?
      options:
        - Android
        - Web
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version
      description: Which app version does the issue occur for you?
      placeholder: ex 2.1.0
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce steps
      description: Please provide the steps to reproduce the issue
      placeholder: |
        - Open X
        - Click on Y
        - Expect Z to be there
    validations:
      required: true
  - type: textarea
    id: specs
    attributes:
      label: Browser or device specs
      description: Please provide the specs of your environment (web browser or device) to help facilitate the reproduction
      placeholder: |
        For Android:
        - Device model: e.g. Redmi 8A, Samsung J6+
        - Android version: e.g. 8, 10, 12
        For Web:
        - Browser: e.g. Chrome, Firefox
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If possible, please include links to the screenshots, or upload them below to explain the issue visually
